### ISSUE TITLE
Unexpected token ] in JSON at position 719

### ISSUE THREAD

**Issue by Joniras** [smnbbrv/ngx-spec#8] opened 2019-03-04 13:11 UTC
Executing one of the example commands:   
`ng g ngx-spec:spec '**/*'`

gives only me the following (and does not do anything):
``` 
Unexpected token ] in JSON at position 719
```

Either the package is broken or i have a configuration error i cannot find.

Also, the error message doesnt really help.

(All my dependencies are up to date)

**Comment by smnbbrv** [comment] 2019-03-04 13:54
you are totally right, the error message is shitty (that's one that comes from @angular/cli)

Please try to change `ngx-spec:spec` to `ngx-spec:specs`. My fault, I wrongly documented it in the README => just fixed that.

```
ng g ngx-spec:specs '**/*'
```

**Comment by Joniras** [comment] 2019-03-04 16:21
The error is still here.

Same error although changed the command to:
`ng g ngx-spec:specs '**/*'`

**Comment by smnbbrv** [comment] 2019-03-04 16:25
could you please share OS that you have and the versions of those packages

- @angular-devkit/core
- @angular-devkit/schematics
- @schematics/angular

?

**Comment by Joniras** [comment] 2019-03-04 16:45
Alright, that was my fault, i had a trailing comma in `angular.json` 
(angular itself didnt bother).

Issue solved (if there cant be anything done to make the error message more obvious).

Thanks for the support though.

**Comment by smnbbrv** [comment] 2019-03-04 19:00
wow, the error is really weird.

This library is just a function which is called by angular cli. You type

```
ng g ...
```

and this actually is that angular cli generates something. Then the lib is that something, or, more correct, lib says how to do it.

This error message comes from angular cli because it could not parse your file. If you return this comma in place and try to generate another component, directive or whatsoever it would result into the same error.

I hope this clarifies the root of the error and how it all works (a bit).

If the issue is solved, could you close it, please?

**Closed as completed** 2019-03-04 19:33 UTC
