### ISSUE TITLE
"type is not defined" for type "component"

### ISSUE THREAD

**Issue by ffderic** [smnbbrv/ngx-spec#11] opened 2020-04-14 07:06 UTC
When trying to use "ng g ngx-spec:spec <some.component.ts>" I just get message "type is not defined" and nothing is generated. It works just fine with services...
Is this a known issue? Any idea?
I use version 2.1.4.

**Comment by BrianJVarley** [comment] 2020-04-27 17:29
Same as @ffderic when I run `ngx-spec` against a component written in typescript. I get the following..

```
$ ng g ngx-spec:spec screen-pops-list.component.ts
type is not defined
```

**Comment by saikiranvadlakonda** [comment] 2020-07-15 11:32
I'm also facing the same error

![image](https://user-images.githubusercontent.com/14762284/87540185-da7d0880-c6bc-11ea-81f2-05fd401f02d6.png)

Any idea, how to resolve it.

**Comment by buddyackerman** [comment] 2020-07-27 18:25
Same issue here.  Not sure why the most used type is not supported.  I'm using NG9.

**Comment by lucb-pc** [comment] 2020-09-01 17:47
I have the exact same problem

**Comment by ThatSpaceGuy** [comment] 2020-09-01 18:20
+1 Same problem - Is anyone working on this?

**Comment by ThatSpaceGuy** [comment] 2020-09-01 18:31
I was able to successfully generate a spec file by running `npm i ngx-spec` for the project that I wanted to generate the file in.  Apparently having it installed globally is not enough - once it was part of the particular project, it generated the desired spec file for a 'component'.  Hopefully this helps someone else with the same issues!

**Comment by joguarino** [comment] 2020-11-10 19:10
Same here, the problem is still present, and neither the solution proposed by @ThatSpaceGuy works for me

**Comment by kylebradshaw** [comment] 2020-12-19 04:33
unfortunately I think the project is essentially dead, it's a non-starter at this point.

**Comment by smnbbrv** [comment] 2020-12-19 08:27
This project is something that was created to solve the particular problem several years ago until Angular team comes with a normal solution. However it looks like they still did not.

There is always an option to make a pull request that fixes the issue or take the project for maintenance. Just complaining does not solve the issue...

**Comment by kylebradshaw** [comment] 2020-12-19 12:48
Agree. Sorry about being so curt. Was working on testing way to late. Thanks for replying to the thread.

**Comment by docsa** [comment] 2020-12-19 18:40
Issue stems from an incompatibility with  angular version 9. It can be worked around by installing locally  angular-cli@8
Hope this helps

**Comment by cacalo** [comment] 2022-01-15 00:10
> This project is something that was created to solve the particular problem several years ago until Angular team comes with a normal solution. However it looks like they still did not.
> 
> There is always an option to make a pull request that fixes the issue or take the project for maintenance. Just complaining does not solve the issue...

I fixed the issue and I want to make a pull request. I need permission to upload my branch.
Could you please do that for me?
Thank you!

**Comment by smnbbrv** [comment] 2022-01-15 09:41
Hi, sounds super!

you can fork the project, make the necessary changes and create a pull request from the fork. This is a normal flow for GitHub projects

**Comment by cacalo** [comment] 2022-01-18 10:14
Fix already merged! This should not longer be an issue :)

**Closed as completed** 2022-01-18 10:56 UTC
